services:
  - type: web
    name: starwars-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /starwars/films/1
    envVars:
      - key: PORT
        value: 8080
      - key: PUBLIC_BASE_URL
        value: https://starwars-api-eu.onrender.com
