
clientConfig {
  baseUrl = "http://localhost:8080"
  //  baseUrl = "https://swapi.dev/api"
  baseUrl = ${?HTTP_CLIENT_BASE_URL}
  cacheSize = 1000
  # requests made in parallel against the upstream api
  maxConcurrency = 8
}
