addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"    % "1.1.4")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"        % "2.6.2")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat"        % "0.5.7")
addSbtPlugin("com.github.sbt"     %% "sbt-native-packager" % "1.11.7")
addSbtPlugin("org.scoverage"      %% "sbt-scoverage"       % "2.4.4")
addSbtPlugin("com.github.sbt"      % "sbt-dynver"          % "5.1.1")
addSbtPlugin("org.scalameta"       % "sbt-mdoc"            % "2.9.2")
