name: Scala CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']
    tags: [v*]

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Check scalafmt
        run: sbt scalafmtCheckAll

      - name: Run test coverage
        run: sbt clean coverage test coverageAggregate

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/scala-*/scoverage-report

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: target/scala-*/coverage-report/cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '50 80'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Determine version
        id: determine_version
        run: echo "VERSION=$(sbt dynverCurrentVersion | tail -n 1 | awk '{print $2}')" >> $GITHUB_ENV

      - name: Generate OpenAPI Docs
        if: github.ref == 'refs/heads/main'
        run: sbt generateOpenAPIDocs

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/openapi
